# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: 'jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.enterprise:jakarta.enterprise.cdi-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.servlet:jakarta.servlet-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'io.smallrye.config:*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss.resteasy:*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.eclipse.jetty:*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'org.jboss.weld.se:*'
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    rebase-strategy: disabled
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
