# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RESTEasy MicroProfile Build and Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '.github/workflows/build.yml'
      - '**/pom.xml'
      - 'config/**'
      - 'context-propagation/**'
      - 'rest-client/**'
      - 'rest-client-base/**'
      - 'resteasy-microprofile-bom/**'
      - 'resteasy-microprofile-test-bom/**'
      - 'testsuite/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/build.yml'
      - '**/pom.xml'
      - 'config/**'
      - 'context-propagation/**'
      - 'rest-client/**'
      - 'rest-client-base/**'
      - 'resteasy-microprofile-bom/**'
      - 'resteasy-microprofile-test-bom/**'
      - 'testsuite/**'
      - 'wildfly/**'

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_CMD: './mvnw -V -B -fae'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDks
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            26
            25
      - name: Build and Test with Java 25 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} clean install
      - name: Build and Test with Java 26 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}' '-Dtest.report.dir=java26'
      - name: Build and Test with Java 21 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}' '-Dtest.report.dir=java21'
      - name: Build and Test with Java 17 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-reports-${{ matrix.os }}
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log

  additional-profiles:
    name: Test with ${{ matrix.profile }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        profile:
          - "'-Dsecurity.manager'"
          - "'-Pee-10'"
          - "'-Dprovision.preview'"

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          # 25 needs to be the latest as it's required for compiling, however we will not test on Java 25
          java-version: |
            17
            21
            25
      - name: Test with Java 17 - ${{ matrix.profile }}
        run: ${{ env.MVN_CMD }} clean install ${{ matrix.profile }} '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}' '-Dtest.report.dir=java17'
      - name: Test with Java 21 - ${{ matrix.profile }}
        run: ${{ env.MVN_CMD }} clean install ${{ matrix.profile }} '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}' '-Dtest.report.dir=java21'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-reports
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Validate Formatting
        run: |
          ${{ env.MVN_CMD }} validate -Pformat-check -Denforcer.skip=true

