# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RESTEasy MicroProfile Integration Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/resteasy-build.yml'
      - '**/pom.xml'
      - 'config/**'
      - 'context-propagation/**'
      - 'rest-client/**'
      - 'rest-client-base/**'
      - 'resteasy-microprofile-bom/**'
      - 'resteasy-microprofile-test-bom/**'
      - 'testsuite/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/resteasy-build.yml'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job and cancel previous ones
concurrency:
  group: 'resteasy-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

env:
  MVN_CMD: './mvnw -V -B -fae'

jobs:
  resteasy-build:
    uses: resteasy/resteasy/.github/workflows/shared-resteasy-build.yml@6.2
    with:
      resteasy-branch: "6.2"
      resteasy-repo: "resteasy/resteasy"

  resteasy-microprofile-build:
    runs-on: ${{ matrix.os }}
    needs: resteasy-build
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout RESTEasy MicroProfile
        uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: resteasy-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf resteasy-maven-repository.tar.gz -C ~
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            26
            25
      - name: Build and Test RESTEasy MicroProfile Java 25 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} clean install '-Dversion.org.jboss.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}'
      - name: Build and Test RESTEasy MicroProfile Java 26 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.jboss.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}' '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}' '-Dtest.report.dir=java26'
      - name: Build and Test RESTEasy MicroProfile Java 21 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.jboss.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}' '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}' '-Dtest.report.dir=java21'
      - name: Build and Test RESTEasy MicroProfile Java 17 - ${{ matrix.os }}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.jboss.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}' '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-reports-${{ matrix.os }}
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log

