# This workflow is for a nightly run against WildFly upstream

name: WildFly Test Build

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/wildfly-build.yml'
      - '**/pom.xml'
      - 'config/**'
      - 'context-propagation/**'
      - 'rest-client/**'
      - 'rest-client-base/**'
      - 'resteasy-microprofile-bom/**'
      - 'resteasy-microprofile-test-bom/**'
      - 'testsuite/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/wildfly-build.yml'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job and cancel previous ones
concurrency:
  group: 'wildfly-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

env:
  MVN_CMD: './mvnw -V -B -fae'

jobs:

  resteasy-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6
      - uses: wildfly-extras/wildfly-nightly-download@v1
        id: wildfly-nightly
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          # Please note the order here of having 25 last as that is the version we want to compile with
          java-version: |
            17
            21
            26
            25
      - name: Build with Maven Java 25
        run: ${{ env.MVN_CMD }} clean install '-Dserver.version=${{ steps.wildfly-nightly.outputs.wildfly-version }}'
      - name: Build with Maven Java 26
        run: ${{ env.MVN_CMD }} verify '-Dserver.version=${{ steps.wildfly-nightly.outputs.wildfly-version }}' '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}' '-Dtest.report.dir=java26'
      - name: Build with Maven Java 21
        run: ${{ env.MVN_CMD }} verify '-Dserver.version=${{ steps.wildfly-nightly.outputs.wildfly-version }}' '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}' '-Dtest.report.dir=java21'
      - name: Build with Maven Java 17
        run: ${{ env.MVN_CMD }} verify '-Dserver.version=${{ steps.wildfly-nightly.outputs.wildfly-version }}' '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}' '-Dtest.report.dir=java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: failure-reports-${{ matrix.os }}
          path: |
            **/surefire-reports/**
            **/failsafe-reports/**
            **/*.log
